package com.nick.towerdefence.Model;

public enum CellNames {
    GRID, PURCHASE, STATUS,
    GRIDCELL,
    PURCHASEBTURRETCELL, PURCHASEMTURRETCELL, PURCHASEATURRETCELL,
    STATUSWAVESCELL, STATUSLEVELNOCELL, STATUSHPCELL,
    STATUSMONEYCELL
}
