package com.nick.towerdefence.Model;

public enum CellNames {
    WALL, PATH,
    GAMEGRID, CONTROL,
    GRIDCELL,
    PURCHASEBTURRETCELL, PURCHASEMTURRETCELL, PURCHASEATURRETCELL,
    STATUSWAVESCELL, STATUSLEVELNOCELL, STATUSHPCELL,
    STATUSMONEYCELL
}
